---
language: python
services: docker

env:
  global:
    - ROLE_REPO_NAME: aem-security-test
    - ROLE_NAME: aem_security_test
    - ROLE_NAMESPACE: aem_design
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora27

install:
  # Install test dependencies.
  - pip install testinfra molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_REPO_NAME $ROLE_NAMESPACE.$ROLE_NAME
  - cd $ROLE_NAMESPACE.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
